# Generated by Django 4.0 on 2022-11-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('opening_crawl', models.TextField(verbose_name='Opening paragraph')),
                ('directors', models.JSONField(default=list, verbose_name='Directors')),
                ('producers', models.JSONField(default=list, verbose_name='Producers')),
                ('release_date', models.DateField(verbose_name='Release date')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=7, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('skin_color', models.CharField(max_length=30, verbose_name='Skin color')),
                ('eye_color', models.CharField(max_length=30, verbose_name='Eye color')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('mass', models.IntegerField(verbose_name='Mass')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Planet Name')),
                ('diameter', models.CharField(max_length=15, verbose_name='Diameter')),
                ('gravity', models.IntegerField(verbose_name='Gravity')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('climate', models.CharField(max_length=30, verbose_name='Climate')),
                ('films', models.ManyToManyField(related_name='films', to='API.Film')),
                ('residents', models.ManyToManyField(related_name='residents', to='API.Resident')),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(related_name='planets', to='API.Planet'),
        ),
    ]
