# Generated by Django 4.0 on 2022-11-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='films',
        ),
    ]
