# Generated by Django 4.0 on 2022-11-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_planet_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.ManyToManyField(related_name='films', to='API.Film')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.resident')),
            ],
        ),
    ]
